package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
	"github.com/zm1th/chipper/internal/ai"
	"github.com/zm1th/chipper/internal/config"
)

var aiClaudeFlag bool

var aiCmd = &cobra.Command{
	Use:   "ai",
	Short: "Generate AI assistant instruction files for this project",
	Args:  cobra.NoArgs,
	RunE:  runAI,
}

func init() {
	aiCmd.Flags().BoolVar(&aiClaudeFlag, "claude", false, "Write .claude/chipper.md")
}

func runAI(_ *cobra.Command, _ []string) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	genClaude := aiClaudeFlag

	if !genClaude {
		var selected []string
		formErr := huh.NewForm(huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("Generate AI instruction files for which tools?").
				Options(
					huh.NewOption("Claude (.claude/chipper.md)", "claude"),
				).
				Value(&selected),
		)).Run()
		if errors.Is(formErr, huh.ErrUserAborted) {
			fmt.Println("Aborted.")
			return nil
		}
		if formErr != nil {
			return formErr
		}
		for _, s := range selected {
			if s == "claude" {
				genClaude = true
			}
		}
	}

	if genClaude {
		if err := writeClaudeFile(cfg); err != nil {
			return err
		}
	}

	return nil
}

func writeClaudeFile(cfg *config.Config) error {
	dir := filepath.Join(cfg.RootDir, ".claude")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create .claude/: %w", err)
	}

	dest := filepath.Join(dir, "chipper.md")

	header := fmt.Sprintf("<!-- Generated by `chipper ai --claude` on %s. Re-run to update. -->\n\n",
		time.Now().Format("2006-01-02"))
	content := header + string(ai.ClaudeTemplate)

	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", dest, err)
	}

	fmt.Printf("Wrote %s\n\n", dest)
	fmt.Println("To load these instructions, add the following line to your CLAUDE.md:")
	fmt.Println()
	fmt.Println("  @.claude/chipper.md")
	fmt.Println()
	return nil
}
